development:
  adapter: mysql2
  database: inthebag_dev
  encoding: utf8mb4
  host: localhost
  username: root
  password:

test:
  adapter: mysql2
  database: inthebag_dev
  encoding: utf8mb4
  host: localhost
  username: root
  password: